# Generated by Django 4.1.7 on 2023-03-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name_plural': 'Yük Sahibi'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'Depolar'},
        ),
    ]
